server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
    output:
      ansi:
        enabled: Always

logging:
  level:
    com.ead: DEBUG
#    root: INFO,
#    org.springframework.web: DEBUG,
#    org.hibernate: INFO

ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
    instance:
      hostname: localhost